var wms_layers = [];

var lyr_precip_0 = new ol.layer.Image({
                            opacity: 1,
                            title: "precip",
                            
                            
                            source: new ol.source.ImageStatic({
                               url: "./layers/precip_0.png",
    attributions: ' ',
                                projection: 'EPSG:3857',
                                alwaysInRange: true,
                                imageExtent: [-20037508.342789, -44927335.427097, 20037508.342789, 44927335.427096]
                            })
                        });
var format_ne_10m_admin_1_states_provinces_1 = new ol.format.GeoJSON();
var features_ne_10m_admin_1_states_provinces_1 = format_ne_10m_admin_1_states_provinces_1.readFeatures(json_ne_10m_admin_1_states_provinces_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ne_10m_admin_1_states_provinces_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_ne_10m_admin_1_states_provinces_1.addFeatures(features_ne_10m_admin_1_states_provinces_1);
var lyr_ne_10m_admin_1_states_provinces_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_ne_10m_admin_1_states_provinces_1, 
                style: style_ne_10m_admin_1_states_provinces_1,
                interactive: true,
                title: '<img src="styles/legend/ne_10m_admin_1_states_provinces_1.png" /> ne_10m_admin_1_states_provinces'
            });

lyr_precip_0.setVisible(true);lyr_ne_10m_admin_1_states_provinces_1.setVisible(true);
var layersList = [lyr_precip_0,lyr_ne_10m_admin_1_states_provinces_1];
lyr_ne_10m_admin_1_states_provinces_1.set('fieldAliases', {'featurecla': 'featurecla', 'scalerank': 'scalerank', 'adm1_code': 'adm1_code', 'diss_me': 'diss_me', 'iso_3166_2': 'iso_3166_2', 'wikipedia': 'wikipedia', 'iso_a2': 'iso_a2', 'adm0_sr': 'adm0_sr', 'name': 'name', 'name_alt': 'name_alt', 'name_local': 'name_local', 'type': 'type', 'type_en': 'type_en', 'code_local': 'code_local', 'code_hasc': 'code_hasc', 'note': 'note', 'hasc_maybe': 'hasc_maybe', 'region': 'region', 'region_cod': 'region_cod', 'provnum_ne': 'provnum_ne', 'gadm_level': 'gadm_level', 'check_me': 'check_me', 'datarank': 'datarank', 'abbrev': 'abbrev', 'postal': 'postal', 'area_sqkm': 'area_sqkm', 'sameascity': 'sameascity', 'labelrank': 'labelrank', 'name_len': 'name_len', 'mapcolor9': 'mapcolor9', 'mapcolor13': 'mapcolor13', 'fips': 'fips', 'fips_alt': 'fips_alt', 'woe_id': 'woe_id', 'woe_label': 'woe_label', 'woe_name': 'woe_name', 'latitude': 'latitude', 'longitude': 'longitude', 'sov_a3': 'sov_a3', 'adm0_a3': 'adm0_a3', 'adm0_label': 'adm0_label', 'admin': 'admin', 'geonunit': 'geonunit', 'gu_a3': 'gu_a3', 'gn_id': 'gn_id', 'gn_name': 'gn_name', 'gns_id': 'gns_id', 'gns_name': 'gns_name', 'gn_level': 'gn_level', 'gn_region': 'gn_region', 'gn_a1_code': 'gn_a1_code', 'region_sub': 'region_sub', 'sub_code': 'sub_code', 'gns_level': 'gns_level', 'gns_lang': 'gns_lang', 'gns_adm1': 'gns_adm1', 'gns_region': 'gns_region', 'min_label': 'min_label', 'max_label': 'max_label', 'min_zoom': 'min_zoom', 'wikidataid': 'wikidataid', 'name_ar': 'name_ar', 'name_bn': 'name_bn', 'name_de': 'name_de', 'name_en': 'name_en', 'name_es': 'name_es', 'name_fr': 'name_fr', 'name_el': 'name_el', 'name_hi': 'name_hi', 'name_hu': 'name_hu', 'name_id': 'name_id', 'name_it': 'name_it', 'name_ja': 'name_ja', 'name_ko': 'name_ko', 'name_nl': 'name_nl', 'name_pl': 'name_pl', 'name_pt': 'name_pt', 'name_ru': 'name_ru', 'name_sv': 'name_sv', 'name_tr': 'name_tr', 'name_vi': 'name_vi', 'name_zh': 'name_zh', 'ne_id': 'ne_id', 'name_he': 'name_he', 'name_uk': 'name_uk', 'name_ur': 'name_ur', 'name_fa': 'name_fa', 'name_zht': 'name_zht', 'FCLASS_ISO': 'FCLASS_ISO', 'FCLASS_US': 'FCLASS_US', 'FCLASS_FR': 'FCLASS_FR', 'FCLASS_RU': 'FCLASS_RU', 'FCLASS_ES': 'FCLASS_ES', 'FCLASS_CN': 'FCLASS_CN', 'FCLASS_TW': 'FCLASS_TW', 'FCLASS_IN': 'FCLASS_IN', 'FCLASS_NP': 'FCLASS_NP', 'FCLASS_PK': 'FCLASS_PK', 'FCLASS_DE': 'FCLASS_DE', 'FCLASS_GB': 'FCLASS_GB', 'FCLASS_BR': 'FCLASS_BR', 'FCLASS_IL': 'FCLASS_IL', 'FCLASS_PS': 'FCLASS_PS', 'FCLASS_SA': 'FCLASS_SA', 'FCLASS_EG': 'FCLASS_EG', 'FCLASS_MA': 'FCLASS_MA', 'FCLASS_PT': 'FCLASS_PT', 'FCLASS_AR': 'FCLASS_AR', 'FCLASS_JP': 'FCLASS_JP', 'FCLASS_KO': 'FCLASS_KO', 'FCLASS_VN': 'FCLASS_VN', 'FCLASS_TR': 'FCLASS_TR', 'FCLASS_ID': 'FCLASS_ID', 'FCLASS_PL': 'FCLASS_PL', 'FCLASS_GR': 'FCLASS_GR', 'FCLASS_IT': 'FCLASS_IT', 'FCLASS_NL': 'FCLASS_NL', 'FCLASS_SE': 'FCLASS_SE', 'FCLASS_BD': 'FCLASS_BD', 'FCLASS_UA': 'FCLASS_UA', 'FCLASS_TLC': 'FCLASS_TLC', });
lyr_ne_10m_admin_1_states_provinces_1.set('fieldImages', {'featurecla': 'TextEdit', 'scalerank': 'Range', 'adm1_code': 'TextEdit', 'diss_me': 'Range', 'iso_3166_2': 'TextEdit', 'wikipedia': 'TextEdit', 'iso_a2': 'TextEdit', 'adm0_sr': 'Range', 'name': 'TextEdit', 'name_alt': 'TextEdit', 'name_local': 'TextEdit', 'type': 'TextEdit', 'type_en': 'TextEdit', 'code_local': 'TextEdit', 'code_hasc': 'TextEdit', 'note': 'TextEdit', 'hasc_maybe': 'TextEdit', 'region': 'TextEdit', 'region_cod': 'TextEdit', 'provnum_ne': 'Range', 'gadm_level': 'Range', 'check_me': 'Range', 'datarank': 'Range', 'abbrev': 'TextEdit', 'postal': 'TextEdit', 'area_sqkm': 'Range', 'sameascity': 'Range', 'labelrank': 'Range', 'name_len': 'Range', 'mapcolor9': 'Range', 'mapcolor13': 'Range', 'fips': 'TextEdit', 'fips_alt': 'TextEdit', 'woe_id': 'Range', 'woe_label': 'TextEdit', 'woe_name': 'TextEdit', 'latitude': 'TextEdit', 'longitude': 'TextEdit', 'sov_a3': 'TextEdit', 'adm0_a3': 'TextEdit', 'adm0_label': 'Range', 'admin': 'TextEdit', 'geonunit': 'TextEdit', 'gu_a3': 'TextEdit', 'gn_id': 'Range', 'gn_name': 'TextEdit', 'gns_id': 'Range', 'gns_name': 'TextEdit', 'gn_level': 'Range', 'gn_region': 'TextEdit', 'gn_a1_code': 'TextEdit', 'region_sub': 'TextEdit', 'sub_code': 'TextEdit', 'gns_level': 'Range', 'gns_lang': 'TextEdit', 'gns_adm1': 'TextEdit', 'gns_region': 'TextEdit', 'min_label': 'TextEdit', 'max_label': 'TextEdit', 'min_zoom': 'TextEdit', 'wikidataid': 'TextEdit', 'name_ar': 'TextEdit', 'name_bn': 'TextEdit', 'name_de': 'TextEdit', 'name_en': 'TextEdit', 'name_es': 'TextEdit', 'name_fr': 'TextEdit', 'name_el': 'TextEdit', 'name_hi': 'TextEdit', 'name_hu': 'TextEdit', 'name_id': 'TextEdit', 'name_it': 'TextEdit', 'name_ja': 'TextEdit', 'name_ko': 'TextEdit', 'name_nl': 'TextEdit', 'name_pl': 'TextEdit', 'name_pt': 'TextEdit', 'name_ru': 'TextEdit', 'name_sv': 'TextEdit', 'name_tr': 'TextEdit', 'name_vi': 'TextEdit', 'name_zh': 'TextEdit', 'ne_id': 'TextEdit', 'name_he': 'TextEdit', 'name_uk': 'TextEdit', 'name_ur': 'TextEdit', 'name_fa': 'TextEdit', 'name_zht': 'TextEdit', 'FCLASS_ISO': 'TextEdit', 'FCLASS_US': 'TextEdit', 'FCLASS_FR': 'TextEdit', 'FCLASS_RU': 'TextEdit', 'FCLASS_ES': 'TextEdit', 'FCLASS_CN': 'TextEdit', 'FCLASS_TW': 'TextEdit', 'FCLASS_IN': 'TextEdit', 'FCLASS_NP': 'TextEdit', 'FCLASS_PK': 'TextEdit', 'FCLASS_DE': 'TextEdit', 'FCLASS_GB': 'TextEdit', 'FCLASS_BR': 'TextEdit', 'FCLASS_IL': 'TextEdit', 'FCLASS_PS': 'TextEdit', 'FCLASS_SA': 'TextEdit', 'FCLASS_EG': 'TextEdit', 'FCLASS_MA': 'TextEdit', 'FCLASS_PT': 'TextEdit', 'FCLASS_AR': 'TextEdit', 'FCLASS_JP': 'TextEdit', 'FCLASS_KO': 'TextEdit', 'FCLASS_VN': 'TextEdit', 'FCLASS_TR': 'TextEdit', 'FCLASS_ID': 'TextEdit', 'FCLASS_PL': 'TextEdit', 'FCLASS_GR': 'TextEdit', 'FCLASS_IT': 'TextEdit', 'FCLASS_NL': 'TextEdit', 'FCLASS_SE': 'TextEdit', 'FCLASS_BD': 'TextEdit', 'FCLASS_UA': 'TextEdit', 'FCLASS_TLC': 'TextEdit', });
lyr_ne_10m_admin_1_states_provinces_1.set('fieldLabels', {'featurecla': 'no label', 'scalerank': 'no label', 'adm1_code': 'no label', 'diss_me': 'no label', 'iso_3166_2': 'no label', 'wikipedia': 'no label', 'iso_a2': 'no label', 'adm0_sr': 'no label', 'name': 'no label', 'name_alt': 'no label', 'name_local': 'no label', 'type': 'no label', 'type_en': 'no label', 'code_local': 'no label', 'code_hasc': 'no label', 'note': 'no label', 'hasc_maybe': 'no label', 'region': 'no label', 'region_cod': 'no label', 'provnum_ne': 'no label', 'gadm_level': 'no label', 'check_me': 'no label', 'datarank': 'no label', 'abbrev': 'no label', 'postal': 'no label', 'area_sqkm': 'no label', 'sameascity': 'no label', 'labelrank': 'no label', 'name_len': 'no label', 'mapcolor9': 'no label', 'mapcolor13': 'no label', 'fips': 'no label', 'fips_alt': 'no label', 'woe_id': 'no label', 'woe_label': 'no label', 'woe_name': 'no label', 'latitude': 'no label', 'longitude': 'no label', 'sov_a3': 'no label', 'adm0_a3': 'no label', 'adm0_label': 'no label', 'admin': 'no label', 'geonunit': 'no label', 'gu_a3': 'no label', 'gn_id': 'no label', 'gn_name': 'no label', 'gns_id': 'no label', 'gns_name': 'no label', 'gn_level': 'no label', 'gn_region': 'no label', 'gn_a1_code': 'no label', 'region_sub': 'no label', 'sub_code': 'no label', 'gns_level': 'no label', 'gns_lang': 'no label', 'gns_adm1': 'no label', 'gns_region': 'no label', 'min_label': 'no label', 'max_label': 'no label', 'min_zoom': 'no label', 'wikidataid': 'no label', 'name_ar': 'no label', 'name_bn': 'no label', 'name_de': 'no label', 'name_en': 'no label', 'name_es': 'no label', 'name_fr': 'no label', 'name_el': 'no label', 'name_hi': 'no label', 'name_hu': 'no label', 'name_id': 'no label', 'name_it': 'no label', 'name_ja': 'no label', 'name_ko': 'no label', 'name_nl': 'no label', 'name_pl': 'no label', 'name_pt': 'no label', 'name_ru': 'no label', 'name_sv': 'no label', 'name_tr': 'no label', 'name_vi': 'no label', 'name_zh': 'no label', 'ne_id': 'no label', 'name_he': 'no label', 'name_uk': 'no label', 'name_ur': 'no label', 'name_fa': 'no label', 'name_zht': 'no label', 'FCLASS_ISO': 'no label', 'FCLASS_US': 'no label', 'FCLASS_FR': 'no label', 'FCLASS_RU': 'no label', 'FCLASS_ES': 'no label', 'FCLASS_CN': 'no label', 'FCLASS_TW': 'no label', 'FCLASS_IN': 'no label', 'FCLASS_NP': 'no label', 'FCLASS_PK': 'no label', 'FCLASS_DE': 'no label', 'FCLASS_GB': 'no label', 'FCLASS_BR': 'no label', 'FCLASS_IL': 'no label', 'FCLASS_PS': 'no label', 'FCLASS_SA': 'no label', 'FCLASS_EG': 'no label', 'FCLASS_MA': 'no label', 'FCLASS_PT': 'no label', 'FCLASS_AR': 'no label', 'FCLASS_JP': 'no label', 'FCLASS_KO': 'no label', 'FCLASS_VN': 'no label', 'FCLASS_TR': 'no label', 'FCLASS_ID': 'no label', 'FCLASS_PL': 'no label', 'FCLASS_GR': 'no label', 'FCLASS_IT': 'no label', 'FCLASS_NL': 'no label', 'FCLASS_SE': 'no label', 'FCLASS_BD': 'no label', 'FCLASS_UA': 'no label', 'FCLASS_TLC': 'no label', });
lyr_ne_10m_admin_1_states_provinces_1.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});